version: "3"
services:
  nginx-proxy:
    image: "davyinsa/nginx-proxy"
    container_name: proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./ssl:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      #- ./nginx/custom.conf:/etc/nginx/conf.d/custom.conf
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      #- HTTPS_METHOD=nohttps
      #- ENABLE_IPV6=true
      - HSTS=off
      #- SSL_POLICY=Mozilla-Modern
      - SSL_POLICY=Mozilla-Intermediate
networks:
  default:
    external:
      name: proxy
