FROM owasp/modsecurity-crs:nginx-alpine
ENV DOCKER_HOST=unix:///tmp/docker.sock
## disable access log for nginx-proxy
ENV DISABLE_ACCESS_LOGS=true
ENV ACCESSLOG=/logs/access.log
ENV ERRORLOG=/logs/error.log
ENV MODSEC_AUDIT_LOG=/logs/audit.log

USER root

## Install s6-overlay
COPY --from=shinsenter/s6-overlay / /
# Install docker-gen
COPY --from=nginxproxy/docker-gen:0.10.4 /usr/local/bin/docker-gen /usr/local/bin/docker-gen
# Copy nginx.tmpl from nginxproxy/nginx-proxy.
# because of https://github.com/nginx-proxy/nginx-proxy/pull/2186, using version 1.2.3
COPY --from=nginxproxy/nginx-proxy:1.2.3 /app/nginx.tmpl /app/nginx.tmpl
# enable gzip by default
ADD https://raw.githubusercontent.com/h5bp/server-configs-nginx/main/h5bp/web_performance/compression.conf /etc/nginx/conf.d/compression-gzip.conf

COPY rootfs /
RUN apk add --no-cache bash && \
    mkdir -p /etc/nginx/certs /logs
WORKDIR /app

ENTRYPOINT ["/init"]
